### ISSUE TITLE
routing: dot in url gives 404 not found

### ISSUE THREAD

**Issue by VallariAg** [ceph/pulpito-ng#71]
In local setup, when there's a dot (".") in the url we get 404 not found.

Example run: vshankar-2024-01-25_13:52:19-fs-wip-vshankar-testing-20240125.044502-testing-default-smithi

To reproduce, start pulpito-ng locally and go to `/runs/vshankar-2024-01-25_13:52:19-fs-wip-vshankar-testing-20240125.044502-testing-default-smithi`

**Comment by tech-rounak** [comment]
I would like to take this issue @VallariAg

**Comment by VallariAg** [comment]
@tech-rounak sure, go ahead!
You can test it by going to `/runs/xxx.xxx` route after setting it up locally. Right now it'll show you 404 not found. When fixed, it will open the Run page (similar to what you would see at `/runs/xxxxxx`)

**Comment by VallariAg** [comment]
That's right!
You can setup teuthology locally, instructions are here: https://github.com/ceph/teuthology/tree/main/docs/docker-compose#teuthology-development-environment-instruction

And integrate pulpito-ng with the teuthology setup to see the data. Instructions to do that are in README: https://github.com/ceph/pulpito-ng?tab=readme-ov-file#integrate-with-teuthology-docker-setup

**Comment by tech-rounak** [comment]
Tried Following the steps mentioned on the docs
`  pulpito:
    build:
      context: ../../../pulpito-ng
    environment:
      REACT_APP_PADDLES_SERVER: http://0.0.0.0:8080
    depends_on:
      paddles:
        condition: service_healthy
      teuthology_api:
        condition: service_healthy
    links:
      - paddles
      - teuthology_api
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8081" ]
      timeout: 5s
      interval: 10s
      retries: 2
    ports:
      - 8081:8081`
      
  when I replace the pulpito services in teuthology docker compose and run it,
  it showing an error because the teuthology_api services is not present on the docker-compose file
  And one more thing am using macOS, does the project require some other configuration..


- [ ] teuthology_api

**Comment by VallariAg** [comment]
Hey, we have a project [teuthology-api](https://github.com/ceph/teuthology-api) which is what that's referring to.
But you don't need to set that up for this issue particularly. You can replace the pulpito service with the below text, and it should work:
```
pulpito:
    build:
      context: ../../../pulpito-ng
    environment:
      VITE_PADDLES_SERVER: http://0.0.0.0:8080
    depends_on:
      paddles:
        condition: service_healthy
    links:
      - paddles
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8081" ]
      timeout: 5s
      interval: 10s
      retries: 2
    ports:
      - 8081:8081
```

Now when you open pulpito, you wouldn't see any runs of the main page. If you wanna explore that, you can schedule runs from inside of the teuthology container:
```
docker exec e886a6b3632f /teuthology/virtualenv/bin/teuthology-suite  --suite teuthology:no-ceph -m testnode -p 75 --filter-out "libcephfs,kclient,stream,centos,rhel" -d ubuntu -D 20.04 --limit 1 /teuthology/containerized_node.yaml
```
(here e886a6b3632f is the teuthology container ID)

Then you'll see a run appear on pulpito. 

I don't think you should face any problem setting this up in arm64 arch, I use the same machine. I have setup docker using [rancher desktop](https://docs.rancherdesktop.io/getting-started/installation/#macos) so maybe that might help.
